# application.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        tamar: hamalka
    spec:
      containers:
      - name: app-container
        image: web-app:v1
        ports:
        - containerPort: 8888
